### ISSUE TITLE
`/obj` initial values are wrong

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1635]
Accessing the initial values of an `/obj` using `dreamObject.ObjectDefinition.Variables[key]` gives the wrong values for some special properties. I assume this also fucks up `initial()` but I haven't test that.

You can see this with `ExportText()` 
In OD:
```
object(".0")
	.0
		type = /obj
		contents = list()
		overlays = list()
		underlays = list()
		vis_contents = list()
		color = null
		transform = object(".0")
			.0
				type = /matrix
		filters = list()
		appearance = null
		locs = list(null)
		glide_size = 0


```
but it should be:
```
object(".0")
    .0
        type = /obj
```

**Comment by wixoaGit** [comment]
`ObjectDefinition.Variables[key]` will give `DreamValue.Null` if the variable is initially a list. This is because it is null when the object is created, and a hidden initialization proc creates the list. This is how it works in BYOND, and leads `initial()` to give null same as BYOND.

I'm not sure yet how you're deciding what values to export in `ExportText()` but you might need to have special handling for these special engine lists?
