### ISSUE TITLE
Don't allocate `DreamList._values` until necessary

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#629]
A continuation of https://github.com/wixoaGit/OpenDream/pull/628 would be to set `DreamList._values` to null whenever it's not actually storing any dreamvalues.

**Comment by Insineer** [comment]
Why is it needed? `_values` is a variable of standard List<T>. [It doesn't allocate any excess memory if it's created empty](https://social.msdn.microsoft.com/Forums/vstudio/en-US/f633c776-835e-4fde-a085-04346ff208a0/when-does-dynamic-memory-allocation-take-place-in-c?forum=clr). Moreover, [it's considered bad practice to use null instead of empty collections](https://stackoverflow.com/questions/1969993/is-it-better-to-return-null-or-empty-collection).

I think it's a bad idea to change _values to null when it's empty before you see any problems while actually profiling.
