### ISSUE TITLE
`DreamList.RemoveValue()` is really slow

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#633]
So slow that it's at the top of the profiler.

**Comment by TheFakeElon** [comment]
Credit probably goes to world list being a normal list
![image](https://user-images.githubusercontent.com/59686430/177453373-e7953c53-9436-4780-a43f-06b9ff693f93.png)
as both `LastIndexOf` and Remove/`RemoveAt` are O(n) operations at worst. 
Making the world list a tree instead of a generic dreamlist might fix this, iirc this is what byond does
